---
- name: Add keys to hosts
  hosts: azure
  tasks:
    - name: Install Key
      authorized_key:
        user: azureuser
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      ignore_errors: true
