---
- name: Add keys to hosts
  hosts: all
  tasks:
    - name: Install Key
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      ignore_errors: true
