

name: Apache-Ansible 


on: [workflow_dispatch]



jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
  
#       - uses: actions/checkout@v3

      - name: Install ansible 
        run: |
             sudo apt-get update
             sudo apt-get install -y software-properties-common
             sudo  apt-add-repository ppa:ansible/ansible
             sudo apt-get update
             sudo apt-get  -y install ansible
        shell: bash 
        
      - name: check out repo
        uses: actions/checkout@v2
        
      - name: ssh-keygen 
        run: |
           #sudo mkdir ~/ansible
           #cd ~/ansible
           ssh-keygen -t rsa -C "ansible" -f ~/.ssh/id_rsa
           ls -ld  ~/.ssh
           chmod 0700 ~/.ssh
           cd ~/.ssh
           ls -la 
           echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcdG4KZZxIWHadytpMqPE+U83nIsKCxtXbbsOCryEd1OESGj6wKFUtB9/1kyGavlieZpt2XEdvtCkrfOtWpZRTjr0jzXpZGi5raR7XeKhUHxudZCy1MSd9LjYS9rB670cun7mZ9Op3W2NjfFKH78ZGRyS8b7Gz5zcQalIIp6sF6caS5fEgZpEhmKRkQrmgkacT31jnSzu3pyolX7ICNCF7T3KRl6D3A04hQrYLEefp7GaSv+Nc2zegwdPw+9FmvD+KrGZamo0ROfab/NLFOCdXAb3uiiMmz8KY4b8s594IZjE043VS4ruFusr4dS2y81TbT66iknEs+hbFZ8fswuAL ec2-jun-17-pem" > ~/.ssh/authorized_keys
           ls -la 
           cat ~/.ssh/id_rsa.pub
           #cat <(echo "selection here") | yes 'y' | command
           #cat <(echo "selection here") | yes 'y' | command
           pwd
        shell: bash
        
        
        
        
#       - name: agent bash 
#         run: |
#            chmod 400 key.pem 
#            eval $(ssh-agent)
#            ssh-agent bash
#            ssh-add key.pem  
#         shell: bash
        
#       - name: agent bash 
#         run: |
#          chmod 400 ~/.ssh/id_rsa
#          eval $(ssh-agent)
#          ssh-agent bash
#          ssh-add ~/.ssh/id_rsa
#         shell: bash
        
        
#       - name: check out repo
#         uses: actions/checkout@v3
        
        
#       - name: list all hosts
#         run: |
#            ansible all --list-hosts
        
#       - name: ping to hosts
#         run: |
#           ansible all --key-file ~/.ssh/id_rsa -i hosts -m ping 
#         shell: bash 
        
#       - name: ping to hosts
#         run: |
#           ansible all --private-key key.pem -i hosts -m ping 
#         shell: bash 
        
#       - name: ssh copy to hosts 
#         run: |
#             ansible-playbook ssh-copy.yml
#         shell: bash 
